### ISSUE TITLE
Project Debugging

### ISSUE THREAD

**Issue by barackm** [barackm/NewYork-Times#9]

**Comment by Coolczycki** [comment]
Missing comments on both; HTML & CSS files. Otherwise, a good project did not found any errors.

**Comment by danmainah** [comment]
Great  work baraka didnt find any issue, just a suggestion try finding shortcodes to reduce the number of code lines,

**Comment by SamanAtashi** [comment]
Looks great man, you rock.

**Comment by chukwuemeka1234** [comment]
I don't see an issue with your code. Good work.
